version: "3.3"
services:
    django:
      build: .
      container_name: GatherCoffee
      command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/usr/src/app/
      ports:
        - "80:8000"
      # environment:
      #   - DEBUG=1
      #   - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 a084742fa316491c8c78564efcbce9e0-9a075eac-vm-80.vlab2.uit.edu.vn [::1]
      