version: "3.3"
   
services:
    django:
      build: .
      container_name: django
      command: python manage.py migrate
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/usr/src/app/
      ports:
        - "80:8000"
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]