version: "3.3"
services:
    django:
      build: .
      container_name: GatherCoffee
      volumes:
        - .:/usr/src/app/
      command: >
        sh -c python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000
      ports:
        - "80:8000"
    
      