# Generated by Django 3.2.9 on 2021-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_data',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account_data',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='account_data',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
