# Generated by Django 3.2.9 on 2021-11-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_account_data_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_data',
            name='money',
            field=models.CharField(blank=True, default='100', max_length=100),
        ),
    ]
