# Generated by Django 3.2.9 on 2021-11-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_account_data_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_data',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
