# Generated by Django 3.2.9 on 2021-11-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_account_data_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_data',
            name='friends',
            field=models.TextField(blank=True),
        ),
    ]
