# Generated by Django 3.2.9 on 2021-11-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_account_data_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_data',
            old_name='friends',
            new_name='friend',
        ),
    ]
