# Generated by Django 4.0.1 on 2022-05-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_account_data_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account_data',
            new_name='Accounts',
        ),
    ]
