# Generated by Django 4.0.1 on 2022-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_accounts_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='checkLogin',
            field=models.TextField(default='0', max_length=2),
        ),
    ]
