# Generated by Django 4.0.1 on 2022-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_account_checklogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='checkLogin',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
